"""Allow NULL for expires_at

Revision ID: 00d9318b1068
Revises: 90a8490eeeae
Create Date: 2025-04-08 22:17:20.915102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00d9318b1068'
down_revision = '90a8490eeeae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
