"""Change salary field in JobListing to min/max integers

Revision ID: 24cc9e2bd4da
Revises: 6ef178704583
Create Date: 2025-07-16 07:03:24.632963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24cc9e2bd4da'
down_revision = '6ef178704583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_max', sa.Integer(), nullable=True))
        batch_op.drop_column('salary_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_amount', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.drop_column('salary_max')
        batch_op.drop_column('salary_min')

    # ### end Alembic commands ###
