"""Added phone and national_id to User

Revision ID: 311575719bd5
Revises: 5d08f8164e49
Create Date: 2025-03-16 23:00:14.725595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311575719bd5'
down_revision = '5d08f8164e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('national_id', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['national_id'])
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('national_id')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
