"""Add bazaar oauth fields

Revision ID: 3604d2812cf6
Revises: 742e3d5b68f1
Create Date: 2025-05-17 05:01:26.608456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3604d2812cf6'
down_revision = '742e3d5b68f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bazaar_account_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('bazaar_refresh_token', sa.Text(), nullable=True))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=11),
               nullable=True)
        batch_op.alter_column('national_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=True)
        batch_op.create_unique_constraint(None, ['bazaar_account_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('national_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=11),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=False)
        batch_op.drop_column('bazaar_refresh_token')
        batch_op.drop_column('bazaar_account_id')

    # ### end Alembic commands ###
