"""image

Revision ID: 369a12f3a962
Revises: 3b4df6ea530d
Create Date: 2025-06-12 12:31:21.453193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369a12f3a962'
down_revision = '3b4df6ea530d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['fcm_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('fcm_token')

    # ### end Alembic commands ###
