"""empty message

Revision ID: 3a9e50d83211
Revises: 627032ae7617
Create Date: 2025-06-29 10:59:57.828663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9e50d83211'
down_revision = '627032ae7617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('ban_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ban_reason')
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
