"""parents

Revision ID: 40d379383554
Revises: 24cc9e2bd4da
Create Date: 2025-07-16 12:17:53.786119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40d379383554'
down_revision = '24cc9e2bd4da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_bot_interaction', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('user1_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('user2_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('receiver_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('conversation_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('product_type',
               existing_type=mysql.ENUM('NEW', 'STOCK', 'USED', 'NEEDS_REPAIR', collation='utf8mb4_unicode_ci'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('product_type',
               existing_type=mysql.ENUM('NEW', 'STOCK', 'USED', 'NEEDS_REPAIR', collation='utf8mb4_unicode_ci'),
               nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('receiver_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('user2_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user1_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('chat_bot_interaction', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
