"""Allow NULL for expires_at

Revision ID: 4d450c319997
Revises: eb4b569f6987
Create Date: 2025-03-18 02:59:02.821925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d450c319997'
down_revision = 'eb4b569f6987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('product_type',
               existing_type=mysql.ENUM('NEW', 'STOCK', 'USED', 'NEEDS_REPAIR'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('product_type',
               existing_type=mysql.ENUM('NEW', 'STOCK', 'USED', 'NEEDS_REPAIR'),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
