"""Add bazaar oauth fields

Revision ID: 4dd758d45a26
Revises: 3604d2812cf6
Create Date: 2025-05-17 05:25:39.175253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd758d45a26'
down_revision = '3604d2812cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bazaar_access_token', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bazaar_access_token')

    # ### end Alembic commands ###
