"""Add profile picture to job models

Revision ID: 51d1a24662f8
Revises: 3a9e50d83211
Create Date: 2025-07-10 11:50:14.894299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d1a24662f8'
down_revision = '3a9e50d83211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=100), nullable=True))

    with op.batch_alter_table('job_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_profile', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    with op.batch_alter_table('job_listing', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
