"""Allow NULL for expires_at

Revision ID: 54304fd43386
Revises: 44dc6db3f094
Create Date: 2025-03-24 00:00:07.899312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54304fd43386'
down_revision = '44dc6db3f094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
