"""image

Revision ID: 627032ae7617
Revises: 369a12f3a962
Create Date: 2025-06-12 13:02:39.432031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627032ae7617'
down_revision = '369a12f3a962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_message_is_read'), ['is_read'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_is_read'))
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
