"""Add job listing and job profile reports

Revision ID: 6ef178704583
Revises: 72fb0a064ec9
Create Date: 2025-07-13 09:02:15.096269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef178704583'
down_revision = '72fb0a064ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listing', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
