"""Add military_status to JobProfile

Revision ID: 72fb0a064ec9
Revises: ca867c7b5bb9
Create Date: 2025-07-12 05:30:14.851632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fb0a064ec9'
down_revision = 'ca867c7b5bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_profile', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
