"""hello

Revision ID: 742e3d5b68f1
Revises: ddec09eceb60
Create Date: 2025-05-10 15:06:05.742872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742e3d5b68f1'
down_revision = 'ddec09eceb60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
