"""Allow NULL for expires_at

Revision ID: 80ea9d0bb00a
Revises: 8bf78157b8bd
Create Date: 2025-03-24 04:36:15.435770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ea9d0bb00a'
down_revision = '8bf78157b8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
