"""Allow NULL for expires_at

Revision ID: 8bf78157b8bd
Revises: 9baa92f8227c
Create Date: 2025-03-24 04:08:19.925964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bf78157b8bd'
down_revision = '9baa92f8227c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('province',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('province',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
