"""Allow NULL for expires_at

Revision ID: be0474d49613
Revises: 00d9318b1068
Create Date: 2025-04-08 22:34:27.429825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be0474d49613'
down_revision = '00d9318b1068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replied_to_id', sa.Integer(), nullable=True))
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('receiver_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('conversation_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'message', ['replied_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('conversation_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('receiver_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('replied_to_id')

    # ### end Alembic commands ###
