"""Allow NULL for expires_at

Revision ID: c6a9b7857937
Revises: 54304fd43386
Create Date: 2025-03-24 03:26:02.854448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6a9b7857937'
down_revision = '54304fd43386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('city')
        batch_op.drop_column('province')

    # ### end Alembic commands ###
