"""Add military_status to JobProfile

Revision ID: ca867c7b5bb9
Revises: 51d1a24662f8
Create Date: 2025-07-12 05:23:13.056519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca867c7b5bb9'
down_revision = '51d1a24662f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('military_status', sa.Enum('NOT_APPLICABLE', 'COMPLETED', 'EXEMPT', 'PENDING', name='militarystatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_profile', schema=None) as batch_op:
        batch_op.drop_column('military_status')

    # ### end Alembic commands ###
