"""Allow NULL for expires_at

Revision ID: d83b5f03a5b5
Revises: None
Create Date: 2025-04-07 06:03:37.970538
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd83b5f03a5b5'
down_revision = None  # هیچ نسخه قبلی ندارد
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        # اضافه کردن قابلیت NULL به expires_at
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        
        # اضافه کردن constraint foreign key
        batch_op.create_foreign_key(None, 'conversation', ['conversation_id'], ['id'])
        
        # حذف ستون های receiver_id و is_read
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        # حذف ستون expires_at
        batch_op.drop_column('expires_at')

        # برگرداندن ستون‌های receiver_id و is_read
        batch_op.add_column(sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('receiver_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        
        # حذف foreign key constraint
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
