"""Add new product attributes

Revision ID: df7c1cc2017d
Revises: f17d5c030faf
Create Date: 2025-07-23 06:53:08.632041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7c1cc2017d'
down_revision = 'f17d5c030faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_electric', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_cordless', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_pneumatic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_body_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('body_only_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_chat_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('is_chat_only')
        batch_op.drop_column('body_only_description')
        batch_op.drop_column('is_body_only')
        batch_op.drop_column('is_pneumatic')
        batch_op.drop_column('is_cordless')
        batch_op.drop_column('is_electric')

    # ### end Alembic commands ###
