"""Allow NULL for expires_at

Revision ID: eb4b569f6987
Revises: cf02997eed32
Create Date: 2025-03-17 03:53:36.221532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb4b569f6987'
down_revision = 'cf02997eed32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
