"""Allow NULL for expires_at

Revision ID: f0e5e8926bec
Revises: 80ea9d0bb00a
Create Date: 2025-03-24 04:42:45.594283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0e5e8926bec'
down_revision = '80ea9d0bb00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),  # تغییر به 1000 کاراکتر
               nullable=False)
        batch_op.drop_column('province')
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('province', mysql.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('address',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
