"""parents

Revision ID: f17d5c030faf
Revises: 400cb9b5f1bd
Create Date: 2025-07-17 07:30:12.829308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17d5c030faf'
down_revision = '400cb9b5f1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('idx_product_search', mysql_prefix='FULLTEXT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('idx_product_search', ['name', 'description', 'brand'], unique=False, mysql_prefix='FULLTEXT')

    # ### end Alembic commands ###
